### ISSUE TITLE
Start project

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#1]
Let's make a Todo list without React. 

The first features list:
- Create and delete Todo notes.
- Store it in localStorage, so we can restart browser with keeping our data.

Don't use any libraries like bootstrap, it's necessary for a front-end developer to know how to use CSS, so it's time to learn it.

You can use gulp and any packages like http-serve or browser-sync to serve your app. And create a npm script `start`. So, your app should start like this: `npm start`.

Please never copy-paste any JS/HTML/CSS code from any sites like StackOverflow and tutorials. You should always type code yourself and it's really very important to understand every line of your code (or to ask a question about some foreign code). 

Don't be shy to use simple code and make errors, but only if it's your own errors. Otherwise, if you use foreign advanced code which you don't understand, I won't be able to understand your real current understanding of programming.

In next issues, we will constantly improve our code and programming style, so it's absolutely OK to have simple code at the beginning.

P.S. Don't forget to create learning repositories in your GitHub account every time when you meet any new npm modules. For example, you can create it for browser sync already. 
I recommend you to use such pattern for any npm modules: learning_npm_<package_name>. I use _npm_ to indicate that it's a npm module. In future, you can start to work with other programming languages. For example, there is a package with the same name `request` in both JavaScript and Python. So it can be two repositories: learning_npm_request (for JS), learning_pip_request (for python). Also if you use my naming patterns you will be able to use this utility - https://github.com/jscraft-org/lrep

I don't update my index page for learning repositories (https://github.com/serge-nikitin/learning), I just type in console `lrep` and it does automatically.

**Comment by odv** [comment]
@serge-nikitin  I've added a first draft of the application containing what I have so far. 
I've made a start script that fires up that gulp task in order to watch for changes inside my HTML, CSS and JS files. I have also added a gitignore file after consulting https://git-scm.com/docs/gitignore so that I won't fill the repo with dependencies.

Thank you very much for that helpful observation. I made sure to type everything on my own and not do any bit of copy/pasting.

As for the app, adding tasks, displaying them and storing them in the localStorage works. I have opted to use **createElement** and **createTextNode** in order to make the code cleaner. Didn't want to use variables with string concatenations and have a lot of spaghetti code.

The only thing that I have left before assigning this issue back to you for review is the **deleteTask** functionality. However, I would like to do some additional debugging and only ask for your input after I've exhausted all my debugging leads.

PS: I've created learning repositories for everything I'm learning so that I can have real proof of my activity. I'm also following your naming convention and will be checking that utility as soon as I'm finished with this issue.

**Comment by serge-nikitin** [comment]
About .gitignore file. I like to have such note on all my projects in .gitignore:
/work.txt

So, I have a work.txt file in the root of my repos where I make any small notes. It can be mini-tasks or I temporary store some passwords or SQL queries, for example.

Without such file, I used to write some temp info in source files, but it's really bad practice because you can forget to remove it later.

But this file /work.txt is not a common practice at all. Other programmers use something different for storing temp info.

But anyway I don't see anything bad to have /work.txt file in your .gitignore. At least it works fine for me. So, maybe it can be useful for you too.

**Comment by odv** [comment]
@serge-nikitin Very useful tip! Thank you very much for sharing it! I was using a rudimentary sticky-notes app and always had a lot of notes but unfortunately I couldn't categorize them and make one for each project so you can imagine the mess I had.

I have implemented the delete functionality so I will assign this back to you for a review and I will start working on the other open issues. Thank you once again!

**Comment by serge-nikitin** [comment]
It looks like there is an mistake with deleting Todo and there are some places with "smelling" code.
But it's OK for this task. I'll tell about them tomorrow, when we have a spoken session, and there will be new issues for them.

So feel free to work with other issues, in general everything is fine.
