### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#2]
Let's use .editorconfig file in the project. It's a good practice to have such file. Check your editor for supporting this feature.

Btw, I recommend you to use vscode, but it's up to you.

**Comment by odv** [comment]
@serge-nikitin I didn't knew about EditorConfig. Consulted http://editorconfig.org/ in order to see why you would need a file like that in your project. 

I went and added a file for this particular project but I will need your input here please because I haven't used a file to define coding styles before. I'm not sure what I should what rules I should add and more importantly, why.

As for the code editor used, I use VisualCode. I see they have native support for EditorConfig.

Thank you in advance!

**Comment by odv** [comment]
@serge-nikitin Based on our Skype discussion, I really understood why editor config is important. I went and researched the rules you have recommended me to use, to make sure I understand all of them. I've also went and read more about trailing commas and created a learning repository with my notes for each of these two topics.

I'm assigning this back to you for a review.
