### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#20]
It will be the last task for this project. We will replace browserify with webpack.

**Comment by serge-nikitin** [comment]
If we already use webpack, we should remove gulp + browser-sync.
Use webpack-dev-server instead.

Also now we should use moment as npm dependencies and via import syntax.

**Comment by odv** [comment]
I've removed gulp + browser-sync and added webpack-dev-server but I have a few questions.

Since I'm using babel-loader, do I still need that *babel-transpile* script? 

Also, now that I've added moment as an npm dependency, do I need to add *browserify* back? I ask because now when I start the webpack-dev-server, I get the following error:

```Uncaught ReferenceError: require is not defined
    at bundle.js:3```
