### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#3]
We should check our JS code by eslint. Let's start with "eslit:recommended" style, so google for it.
Create a new npm script: `npm run eslint` for it. Also add eslint support to your editor.

But further, we will use eslint-config-airbnb.

**Comment by odv** [comment]
@serge-nikitin  I've added eslint and the .eslintrc config. However I'm a bit puzzled because if I check the first line of my **script.js** file, the keyword **const** is underlined with red and upon hovering it, the following popup is displayed:

`[eslint] Parsing error: The keyword 'const' is reserved.`

I think it's because of the recommended rules, correct?

As for the editor, I've added the ESLint plugin for Visual Studio Code:

![plugins](https://user-images.githubusercontent.com/5067625/30514767-7268d970-9b24-11e7-836e-bc25a4b4afdd.jpg)


I will assign this back to you for review. Thank you so much.

**Comment by serge-nikitin** [comment]
try this

```
{
  "extends": "eslint:recommended",
  "env": {
    "es6": true,
    "browser": true
  }
}

```

Just read about "env" section.
"es6": true -- It makes our ES6 code as valid

**Comment by odv** [comment]
@serge-nikitin  I've read about the "env" section to really understand what is happening under the hood, here: https://eslint.org/docs/user-guide/configuring

Thank you so much for your input! I'll assign this back to you for review.

**Comment by serge-nikitin** [comment]
We can use eslint for linting ./gulfile.js too. A hint: you need to add env: node for it, to support `require`.

**Comment by odv** [comment]
@serge-nikitin Thank you for the useful tip and for the hint. I went to the documentation page again, configured my **.eslintrc** and **package.json** again and I also did a test to be sure that the script I added in my **package.json** lints both location because my **gulpfile.js** is not in **app/scripts/...**.

I went and broke my gulp file + scripts file and after that started the linter. It outputs errors in both files so judging from this, it seems to be working fine now. I went and reverted the errors shortly after that.

Once again, thank you. Assigning this back to you for a review.
