### ISSUE TITLE
Creation time of todo notes

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-2#4]
Let's store not only Todo text but also let's store creation time of it. You can use `moment` library for time formatting.

**Comment by odv** [comment]
@serge-nikitin I am not sure if I've over-complicated things here or not. 
I can't use **require** for the web so after some time spent online, researching, I have found http://browserify.org/
I've used it as a bundler in order to use npm moment module inside my code.  

The good thing is that I learned something new: **moment** and **browserify**

I will need your input here. Guess I can also use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by serge-nikitin** [comment]
No, we will use `import` syntax and babel. Now you can import moment just via <script src=".."> syntax globally.

We can use both internal Date and moment library. We need moment library only for formatting.

But I think you are right. Let's for this issue use only Date. And we will add moment after babel's task.

**Comment by serge-nikitin** [comment]
I don't recommend you to use browserify, because we anyway have to learn in future webpack.

Nowadays webpack is standard de-facto, especially for React ecosystem.

**Comment by serge-nikitin** [comment]
Also I recommend you to use such tool like npm trends - 
http://www.npmtrends.com/webpack-vs-browserify

It's useful to compare trends of two different technologies. Also check trends for 1 year period for webpack + browserify.

**Comment by serge-nikitin** [comment]
But anyway you already have to add a new learning repo for browserify :)

**Comment by serge-nikitin** [comment]
Sorry, I've forgotten about bundling problem. It's not enough to have only babel, we also need a bundler. So you are absolutely right with browserify. Now we really need it.

In future we will replace it with webpack, but we really need it.

**Comment by odv** [comment]
@serge-nikitin First of all, thanks for all your helpful input. I didn't knew about  npm-trends and what  webpack does. Should I leave everything as it is https://github.com/jscraft-org/mentoring-project-2/commit/e4b9e5db5026c7e52b8e76a0820c9f77d8aee7ea or revert back to using the **new Date()** provided by JavaScript?

**Comment by serge-nikitin** [comment]
Yes, let's leave moment + browserify.

But you shouldn't commit any bundled files in repo. Just add in .gitignore
/path/to/bundle.js

**Comment by odv** [comment]
@serge-nikitin I had some issues with the gitignore rule. It kept recording changes in bundle.js so after some research/experimenting, I found out that it was because of a caching issue. 

Also have to make a GIT repository and populate it with what I have learned.  :)

Thank you once again for that helpful observation. I'm assigning this back to you for review.

**Comment by serge-nikitin** [comment]
I've remembered why I had a plan to do it first without any bundlers. I wanted to show you, in next issue, one problem that your code had, but Browserify interferes it. 

So, yes, please remove Browserify now. We will add it in a new task later.

Install moment.js just via <script src='/lib/moment.js'></script> tag.

**Comment by odv** [comment]
@serge-nikitin I see. I've removed browserify/momentjs npm module and replaced them with a normal script tag that points to **moment.js**

Thank you!
